name: Build & Deploy Container to Slot

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  RG: rg-WebProgramming1-Fall2025-bs
  WEBAPP: wp1-brent-presley-fa25
  SLOT: container-demo
  ACR_NAME: wp1fa25acr                  # no .azurecr.io suffix
  IMAGE_NAME: wp1app                    # repo name inside ACR

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login (Service Principal)
        uses: azure/login@v2
        with:
          creds: >
            {"clientId":"${{ secrets.AZURE_CLIENT_ID }}",
             "clientSecret":"${{ secrets.AZURE_CLIENT_SECRET }}",
             "tenantId":"${{ secrets.AZURE_TENANT_ID }}",
             "subscriptionId":"${{ secrets.AZURE_SUBSCRIPTION_ID }}"}

      - name: Build image (Dockerfile in project directory)
        run: |
          TAG=${{ github.sha }}
          docker build -t $ACR_NAME.azurecr.io/$IMAGE_NAME:$TAG ./deploymentfall25/deploymentfall25
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: ACR Login
        run: az acr login --name $ACR_NAME

      - name: Push image to ACR
        run: docker push $ACR_NAME.azurecr.io/$IMAGE_NAME:${TAG}

      - name: Point SLOT to new image
        run: |
          az webapp config container set \
            -g $RG -n $WEBAPP --slot $SLOT \
            --docker-custom-image-name $ACR_NAME.azurecr.io/$IMAGE_NAME:${TAG} \
            --docker-registry-server-url https://$ACR_NAME.azurecr.io

      # (Idempotent) make sure port is set for Linux container apps
      - name: Ensure WEBSITES_PORT=8080 on slot
        run: |
          az webapp config appsettings set \
            -g $RG -n $WEBAPP --slot $SLOT \
            --settings WEBSITES_PORT=8080

      - name: Restart slot
        run: az webapp restart -g $RG -n $WEBAPP --slot $SLOT
